// Module EPI : vue par agent, recherche, changement avec confirmation du n° et alarmes de conflit.
// Lancement : node _tests/epi.test.mjs  (depuis la racine du dépôt)
import { createRequire } from 'node:module'; import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
const require = createRequire(import.meta.url);
let chromium; try { ({ chromium } = require('playwright')); } catch (e) { ({ chromium } = require('/opt/node22/lib/node_modules/playwright')); }
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..'), SC = process.argv[2] || os.tmpdir();
const T = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.json': 'application/json' };
const srv = http.createServer((q, r) => { let f = path.join(ROOT, decodeURIComponent(new URL(q.url, 'http://x').pathname)); if (fs.existsSync(f) && fs.statSync(f).isDirectory()) f = path.join(f, 'index.html'); if (!fs.existsSync(f)) { r.writeHead(404); r.end(); return; } r.writeHead(200, { 'content-type': T[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(r); }).listen(0);
const B = `http://127.0.0.1:${srv.address().port}`;
const br = await chromium.launch(); const errs = []; let fails = 0;
const ok = (c, m) => { console.log((c ? 'OK   ' : 'ÉCHEC ') + m); if (!c) fails++; };
const ctx = await br.newContext({ viewport: { width: 1360, height: 920 } });
await ctx.addInitScript(() => { sessionStorage.setItem('vbs-session', JSON.stringify({ token: null, role: 'habillement', name: 'Adc. L. Perrin', matricule: 'HAB-0005', offline: true })); localStorage.setItem('vbs-tour-habillement', '1'); });
const pg = await ctx.newPage(); pg.on('pageerror', e => errs.push(e.message));
const wait = (t = 400) => pg.waitForTimeout(t);
const D = () => pg.evaluate(() => { const d = VBSApp.getDb(); return { tenues: d.tenues.map(t => ({ id: t.id, numero: t.numero, type: t.type, agent: t.agent, statut: t.statut })), users: d.users.map(u => ({ id: u.id, name: u.name, matricule: u.matricule, role: u.role })) }; });
await pg.goto(B + '/cmr-pompier/espace.html#epi-agents'); await wait(900);
ok((await pg.locator('#page-title').innerText()) === 'Par agent', 'Page « Par agent » dans le menu du référent EPI');
ok(await pg.locator('.epi-card').count() > 5 && await pg.locator('.epi-card').first().locator('tr').count() === 3, 'Une carte par agent, avec veste, pantalon et cagoule');
let d = await D();
const leroy = d.users.find(u => u.name === 'J. Leroy'), martin = d.users.find(u => u.name === 'A. Martin');
await pg.fill('#e-q', 'leroy'); await wait();
ok(await pg.locator('.epi-card').count() === 1 && (await pg.locator('.epi-card h3').innerText()).includes('Leroy'), 'Recherche par nom');
const mVeste = d.tenues.find(t => t.agent === martin.id && t.type === 'veste');
await pg.fill('#e-q', mVeste.numero); await wait();
ok(await pg.locator('.epi-card').count() === 1 && (await pg.locator('.epi-card h3').innerText()).includes('Martin') && await pg.locator('.epi-hit').count() === 1 && await pg.locator('tr.hit').count() === 1, 'Recherche par n° d\'EPI : porteur trouvé et ligne surlignée');
await pg.fill('#e-q', 'leroy'); await wait();
await pg.click(`[data-chg="${leroy.id}|veste"]`); await wait(300);
const row = pg.locator('dialog .chg-row[data-ty="veste"]');
const lVeste = d.tenues.find(t => t.agent === leroy.id && t.type === 'veste');
await row.locator('[data-cur]').fill('V-9999'); await wait(100);
ok(!(await pg.locator('dialog .chg-row[data-ty="cagoule"] .chg-in').isVisible()) && !(await row.locator('.chg-force').isVisible()), 'Éléments non cochés repliés');
ok((await row.locator('[data-msgs]').innerText()).includes('ne correspond pas'), 'N° actuel erroné : refusé');
await row.locator('[data-cur]').fill(mVeste.numero); await wait(100);
ok(await row.locator('.epi-msg.alarm').count() >= 1 && (await row.locator('.epi-msg.alarm').first().innerText()).includes('Martin'), 'N° actuel d\'un autre agent : alarme de conflit');
await row.locator('[data-cur]').fill(lVeste.numero.toLowerCase());
await row.locator('[data-newn]').fill(mVeste.numero); await wait(100);
ok((await row.locator('.epi-msg.alarm').innerText()).includes('déjà attribuée à') && await row.locator('.chg-force').isVisible(), 'Nouveau n° déjà attribué : alarme + confirmation proposée');
await pg.screenshot({ path: SC + '/epi-conflit.png' });
await pg.click('dialog [data-act="0"]'); await wait(300);
ok((await pg.locator('dialog .modal-err').innerText()).includes('Conflit'), 'Enregistrement bloqué tant que le conflit n\'est pas confirmé');
const pant = d.tenues.find(t => t.type === 'surpantalon' && t.statut === 'en_stock');
await row.locator('[data-newn]').fill(pant.numero); await wait(100);
ok((await row.locator('[data-msgs]').innerText()).includes('pas une veste'), 'Mauvais type d\'EPI : conflit');
const dirty = d.tenues.find(t => t.type === 'veste' && t.statut === 'contaminee' && !t.agent) || d.tenues.find(t => t.type === 'veste' && t.statut === 'au_lavage');
await row.locator('[data-newn]').fill(dirty.numero); await wait(100);
ok(/contaminée|au lavage/.test(await row.locator('[data-msgs]').innerText()), 'Tenue contaminée ou au lavage : refusée');
await row.locator('[data-newn]').fill(mVeste.numero); await wait(100);
await row.locator('[data-force]').check(); await wait(100);
await pg.click('dialog [data-act="0"]'); await wait(900);
d = await D();
const nv = d.tenues.find(t => t.id === mVeste.id), old = d.tenues.find(t => t.id === lVeste.id);
ok(nv.agent === leroy.id && nv.statut === 'en_service', 'Conflit confirmé : tenue réattribuée à J. Leroy');
ok(!old.agent && old.statut === 'contaminee', 'Ancienne tenue de J. Leroy : à laver');
ok(!d.tenues.some(t => t.agent === martin.id && t.type === 'veste'), 'A. Martin n\'a plus cette veste');
// Changement simple depuis le stock
const stockV = d.tenues.find(t => t.type === 'cagoule' && t.statut === 'en_stock'), lCag = d.tenues.find(t => t.agent === leroy.id && t.type === 'cagoule');
await pg.click(`[data-chg="${leroy.id}|cagoule"]`); await wait(300);
const r2 = pg.locator('dialog .chg-row[data-ty="cagoule"]');
await r2.locator('[data-cur]').fill(lCag.numero); await r2.locator('[data-newn]').fill(stockV.numero); await wait(100);
ok((await r2.locator('.epi-msg.ok').count()) >= 1 && !(await r2.locator('.epi-msg.alarm').count()), 'Tenue en stock : aucune alarme');
await pg.click('dialog [data-act="0"]'); await wait(900);
d = await D();
ok(d.tenues.find(t => t.id === stockV.id).agent === leroy.id, 'Changement depuis le stock enregistré');
const hist = await pg.evaluate(() => VBSApp.getDb().mouvements_epi.filter(m => m.type === 'changement').map(m => m.motif).join(' | '));
ok(hist.includes('conflit confirmé') && hist.includes('→'), 'Historique : ancien → nouveau n° et conflit confirmé tracés');
// Modifier une tenue avec un n° déjà utilisé
await pg.goto(B + '/cmr-pompier/espace.html#tenues'); await wait(700);
await pg.click('[data-tact^="modifier|"]'); await wait(300);
await pg.fill('#tn-num', stockV.numero); await pg.click('dialog [data-act="0"]'); await wait(300);
ok((await pg.locator('dialog .modal-err').innerText()).includes('existe déjà'), 'Modifier : n° déjà utilisé refusé');
console.log(errs.length ? 'ÉCHEC erreurs JS ' + errs.join(' / ') : 'OK   aucune erreur JS'); if (errs.length) fails++;
console.log(fails ? fails + ' échec(s)' : 'Tout est OK'); process.exitCode = fails ? 1 : 0;
await br.close(); srv.close();
